/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JapaneseNovelToolPlugin
});
module.exports = __toCommonJS(main_exports);
var import_view = require("@codemirror/view");
var import_language = require("@codemirror/language");
var import_state = require("@codemirror/state");
var import_obsidian2 = require("obsidian");

// src/parser.ts
var ANNOTATION_START = "\u300A";
var NOVEL_RUBY_REGEXP = /(?:(?:[|｜]?(?<body1>[一-龠々仝〆〇ヶ]+?))|(?:[|｜](?<body2>[^|｜]+?)))《(?<ruby>.+?)》/gm;
var KAKUYOMU_EMPHASIS_REGEXP = /《《(?<body>.+?)》》/gm;
var NOVEL_RUBY_STICKY_REGEXP = /(?:(?:[|｜]?(?<body1>[一-龠々仝〆〇ヶ]+?))|(?:[|｜](?<body2>[^|｜]+?)))《(?<ruby>.+?)》/y;
var RUBY_CANDIDATE_CHAR_REGEXP = /[|｜一-龠々仝〆〇ヶ]/;
function parseNovelMarkup(input, enableKakuyomuEmphasis) {
  var _a, _b, _c;
  const tokens = [];
  let plainStart = 0;
  let index = 0;
  const flushPlainText = (end) => {
    if (end <= plainStart) return;
    const text = input.slice(plainStart, end);
    const last = tokens[tokens.length - 1];
    if ((last == null ? void 0 : last.type) === "text") {
      last.text += text;
      return;
    }
    tokens.push({ type: "text", text });
  };
  while (index < input.length) {
    const char = input.charAt(index);
    if (enableKakuyomuEmphasis && char === ANNOTATION_START && input.startsWith("\u300A\u300A", index)) {
      const end = input.indexOf("\u300B\u300B", index + 2);
      if (end !== -1) {
        flushPlainText(index);
        tokens.push({ type: "emphasis", text: input.slice(index + 2, end) });
        index = end + 2;
        plainStart = index;
        continue;
      }
    }
    if (RUBY_CANDIDATE_CHAR_REGEXP.test(char)) {
      NOVEL_RUBY_STICKY_REGEXP.lastIndex = index;
      const rubyMatch = NOVEL_RUBY_STICKY_REGEXP.exec(input);
      if (rubyMatch) {
        const base = ((_a = rubyMatch.groups) == null ? void 0 : _a.body1) || ((_b = rubyMatch.groups) == null ? void 0 : _b.body2) || "";
        const ruby = ((_c = rubyMatch.groups) == null ? void 0 : _c.ruby) || "";
        flushPlainText(index);
        if (isEmphasisAnnotation(ruby)) {
          tokens.push({ type: "emphasis", text: base });
        } else {
          tokens.push({ type: "ruby", base, ruby });
        }
        index += rubyMatch[0].length;
        plainStart = index;
        continue;
      }
    }
    index += 1;
  }
  flushPlainText(input.length);
  return tokens;
}
function stripNovelMarkup(input, enableKakuyomuEmphasis) {
  return parseNovelMarkup(input, enableKakuyomuEmphasis).map((token) => {
    if (token.type === "ruby") return token.base;
    if (token.type === "emphasis") return token.text;
    return token.text;
  }).join("");
}
function removeNovelMarkup(input, enableKakuyomuEmphasis) {
  return stripNovelMarkup(input, enableKakuyomuEmphasis);
}
function isEmphasisAnnotation(annotation) {
  const chars = Array.from(annotation);
  if (chars.length === 0) {
    return false;
  }
  if (chars.every((char) => char === "\u30FB" || char === "\uFE45" || char === "\uFE46")) {
    return true;
  }
  return chars.every((char) => char === chars[0]) && !/[\p{Letter}\p{Number}\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(chars[0]);
}

// src/count.ts
var COMMENT_PATTERN = /%%[\s\S]*?%%/g;
var NEWLINE_PATTERN = /\r\n|\r|\n/g;
var WHITESPACE_EXCEPT_NEWLINES_PATTERN = /[^\S\r\n]+/g;
var ATX_HEADING_PATTERN = /^(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$/;
var SETEXT_HEADING_PATTERN = /^[ \t]*(=+|-+)[ \t]*$/;
var FENCE_PATTERN = /^[ \t]{0,3}(`{3,}|~{3,})/;
var CALLOUT_START_PATTERN = /^[ \t]*>[ \t]*\[![^\]]+\]/i;
var BLOCKQUOTE_PATTERN = /^[ \t]*>/;
function countNovelCharacters(markdown, options) {
  return prepareTextForCount(markdown, options).length;
}
function prepareTextForCount(source, options) {
  let text = source;
  if (options.excludeComments) {
    text = text.replace(COMMENT_PATTERN, "");
  }
  if (options.excludeCallouts) {
    text = removeCallouts(text);
  }
  if (options.excludeHeadings) {
    text = removeHeadingLines(text);
  }
  if (options.excludeRuby) {
    text = stripNovelMarkup(text, options.enableKakuyomuEmphasis);
  }
  if (options.excludeMarkdownControls) {
    text = stripMarkdownControls(text);
  }
  if (options.excludeWhitespace) {
    text = text.replace(WHITESPACE_EXCEPT_NEWLINES_PATTERN, "");
  }
  if (options.excludeNewlines) {
    text = text.replace(NEWLINE_PATTERN, "");
  }
  return text;
}
function getHeadingSections(source, options) {
  const lines = splitLines(source);
  const headings = findHeadings(lines);
  const endLines = getSectionEndLines(headings, lines.length);
  return headings.map((heading, index) => {
    const sectionText = lines.slice(heading.line + 1, endLines[index]).join("\n");
    return {
      ...heading,
      count: countNovelCharacters(sectionText, options)
    };
  });
}
function getSectionEndLines(headings, totalLines) {
  const endLines = headings.map(() => totalLines);
  const stack = [];
  headings.forEach((heading, index) => {
    while (stack.length > 0 && stack[stack.length - 1].level >= heading.level) {
      const open = stack.pop();
      if (open) {
        endLines[open.index] = heading.line;
      }
    }
    stack.push({ index, level: heading.level });
  });
  return endLines;
}
function getHeadingSectionRangeAtOffset(source, offset) {
  var _a, _b;
  const lines = splitLines(source);
  const lineStarts = getLineStarts(source, lines);
  const targetLine = findLineAtOffset(lineStarts, offset);
  const headings = findHeadings(lines);
  const ancestors = [];
  for (let index = 0; index < headings.length; index += 1) {
    const heading = headings[index];
    if (heading.line > targetLine) {
      break;
    }
    while (ancestors.length > 0 && ancestors[ancestors.length - 1].heading.level >= heading.level) {
      ancestors.pop();
    }
    ancestors.push({ heading, index });
  }
  const current = ancestors[ancestors.length - 1];
  if (!current) {
    return void 0;
  }
  const nextHeading = headings.slice(current.index + 1).find((candidate) => candidate.level <= current.heading.level);
  const endLine = (_a = nextHeading == null ? void 0 : nextHeading.line) != null ? _a : lines.length;
  const isAtx = ATX_HEADING_PATTERN.test((_b = lines[current.heading.line]) != null ? _b : "");
  const bodyStartLine = current.heading.line + (isAtx ? 1 : 2);
  return { headingLine: current.heading.line, bodyStartLine, endLine };
}
function getHeadingAncestorsFromHeadings(headings, targetLine) {
  const ancestors = [];
  for (const heading of headings) {
    if (heading.line > targetLine) {
      break;
    }
    while (ancestors.length > 0 && ancestors[ancestors.length - 1].level >= heading.level) {
      ancestors.pop();
    }
    ancestors.push(heading);
  }
  return ancestors;
}
function formatCount(count) {
  return count.toLocaleString("en-US");
}
function stripMarkdownControls(markdown) {
  return markdown.replace(/```[\s\S]*?```/g, (match) => match.replace(/```[^\n]*\n?|```/g, "")).replace(/`([^`]*)`/g, "$1").replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/!\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g, "").replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2").replace(/\[\[([^\]]+)\]\]/g, "$1").replace(/^(\s{0,3})#{1,6}\s+/gm, "$1").replace(/^(\s{0,3})([-*+]|\d+\.)\s+/gm, "$1").replace(/^(\s{0,3})>\s?/gm, "$1").replace(/[*_~=#|\\>-]/g, "");
}
function removeCallouts(source) {
  const lines = splitLines(source);
  const result = [];
  let inCallout = false;
  for (const line of lines) {
    if (!inCallout && CALLOUT_START_PATTERN.test(line)) {
      inCallout = true;
      continue;
    }
    if (inCallout) {
      if (BLOCKQUOTE_PATTERN.test(line) || line.trim() === "") {
        continue;
      }
      inCallout = false;
    }
    result.push(line);
  }
  return result.join("\n");
}
function removeHeadingLines(source) {
  const lines = splitLines(source);
  const headings = new Set(findHeadings(lines).map((heading) => heading.line));
  return lines.filter((_, index) => !headings.has(index)).join("\n");
}
function findHeadings(lines) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  const headings = [];
  let fenceMarker = null;
  for (let line = 0; line < lines.length; line += 1) {
    const value = (_a = lines[line]) != null ? _a : "";
    const fenceMatch = value.match(FENCE_PATTERN);
    if (fenceMatch) {
      const marker = (_b = fenceMatch[1]) != null ? _b : "";
      if (fenceMarker === null) {
        fenceMarker = marker;
      } else if (marker[0] === fenceMarker[0] && marker.length >= fenceMarker.length) {
        fenceMarker = null;
      }
      continue;
    }
    if (fenceMarker !== null || BLOCKQUOTE_PATTERN.test(value)) {
      continue;
    }
    const atxMatch = value.match(ATX_HEADING_PATTERN);
    if (atxMatch) {
      headings.push({
        line,
        level: (_d = (_c = atxMatch[1]) == null ? void 0 : _c.length) != null ? _d : 1,
        text: (_f = (_e = atxMatch[2]) == null ? void 0 : _e.trim()) != null ? _f : ""
      });
      continue;
    }
    const nextLine = (_g = lines[line + 1]) != null ? _g : "";
    const setextMatch = nextLine.match(SETEXT_HEADING_PATTERN);
    if (value.trim() !== "" && setextMatch) {
      headings.push({
        line,
        level: ((_h = setextMatch[1]) == null ? void 0 : _h.startsWith("=")) ? 1 : 2,
        text: value.trim()
      });
      line += 1;
    }
  }
  return headings;
}
function splitLines(source) {
  return source.split(/\r\n|\r|\n/);
}
function getLineStarts(source, lines) {
  const starts = [];
  let offset = 0;
  for (const line of lines) {
    starts.push(offset);
    offset += line.length + 1;
  }
  if (source.endsWith("\n")) {
    starts.push(source.length);
  }
  return starts;
}
function findLineAtOffset(lineStarts, offset) {
  var _a, _b;
  let low = 0;
  let high = lineStarts.length - 1;
  while (low <= high) {
    const mid = Math.floor((low + high) / 2);
    const start = (_a = lineStarts[mid]) != null ? _a : 0;
    const next = (_b = lineStarts[mid + 1]) != null ? _b : Number.POSITIVE_INFINITY;
    if (offset < start) {
      high = mid - 1;
    } else if (offset >= next) {
      low = mid + 1;
    } else {
      return mid;
    }
  }
  return Math.max(0, lineStarts.length - 1);
}

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enableIndentation: true,
  showWhitespaceMarks: false,
  showLineBreakMarks: false,
  enableRubyRendering: true,
  enableKakuyomuEmphasis: true,
  rubySizeRatio: 0.5,
  emphasisInsertFormat: "kakuyomu",
  emphasisMark: "\uFE45",
  enableCharacterCount: true,
  showHeadingCounts: true,
  countPrefix: "",
  countSuffix: "\u6587\u5B57",
  excludeWhitespaceFromCount: true,
  excludeNewlinesFromCount: true,
  excludeRubyFromCount: true,
  excludeCalloutsFromCount: true,
  excludeCommentsFromCount: true,
  excludeHeadingsFromCount: false,
  excludeMarkdownControlsFromCount: false
};
var JapaneseNovelToolSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("jnt-settings");
    containerEl.createEl("h2", { text: "\u5B57\u4E0B\u3052" });
    new import_obsidian.Setting(containerEl).setName("\u65E5\u672C\u8A9E\u306E\u5B57\u4E0B\u3052\u3092\u8868\u793A").setDesc("\u884C\u982D\u306E\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u3092Reading view\u3067\u5B57\u4E0B\u3052\u3068\u3057\u3066\u8868\u793A\u3057\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableIndentation).onChange(async (value) => {
      this.plugin.settings.enableIndentation = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    containerEl.createEl("h2", { text: "\u53EF\u8996\u5316" });
    new import_obsidian.Setting(containerEl).setName("\u7A7A\u767D\u3092\u53EF\u8996\u5316").setDesc("\u30A8\u30C7\u30A3\u30BF\u3067\u5168\u89D2\u30B9\u30DA\u30FC\u30B9\u30FB\u30BF\u30D6\u306B\u30DE\u30FC\u30AF\u3092\u8868\u793A\u3057\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.showWhitespaceMarks).onChange(async (value) => {
      this.plugin.settings.showWhitespaceMarks = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6539\u884C\u3092\u53EF\u8996\u5316").setDesc("\u30A8\u30C7\u30A3\u30BF\u3067\u884C\u672B\u306B\u6539\u884C\u30DE\u30FC\u30AF\uFF08\u21B5\uFF09\u3092\u8868\u793A\u3057\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.showLineBreakMarks).onChange(async (value) => {
      this.plugin.settings.showLineBreakMarks = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    containerEl.createEl("h2", { text: "\u30EB\u30D3" });
    new import_obsidian.Setting(containerEl).setName("\u30EB\u30D3\u3068\u508D\u70B9\u3092\u8868\u793A").setDesc("\uFF5C\u672C\u6587\u300A\u30EB\u30D3\u300B\u3001\u672C\u6587\u300A\u30EB\u30D3\u300B\u3001\uFF5C\u672C\u6587\u300A\u30FB\u300B\u3092\u8868\u793A\u7528HTML\u306B\u5909\u63DB\u3057\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableRubyRendering).onChange(async (value) => {
      this.plugin.settings.enableRubyRendering = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u30AB\u30AF\u30E8\u30E0\u5F62\u5F0F\u306E\u508D\u70B9").setDesc("\u300A\u300A\u672C\u6587\u300B\u300B\u3092\u508D\u70B9\u3068\u3057\u3066\u8868\u793A\u3057\u307E\u3059\u3002\u30EB\u30D3\u3068\u306F\u540C\u6642\u306B\u89E3\u91C8\u3057\u307E\u305B\u3093\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableKakuyomuEmphasis).onChange(async (value) => {
      this.plugin.settings.enableKakuyomuEmphasis = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u30EB\u30D3\u30B5\u30A4\u30BA\u6BD4\u7387").setDesc("\u672C\u6587\u30B5\u30A4\u30BA\u306B\u5BFE\u3059\u308B\u30EB\u30D3\u6587\u5B57\u30B5\u30A4\u30BA\u306E\u6BD4\u7387\u3067\u3059\u3002\u30C7\u30D5\u30A9\u30EB\u30C8\u306F 0.5 \u3067\u3059\u3002").addText((text) => text.setPlaceholder("0.5").setValue(String(this.plugin.settings.rubySizeRatio)).onChange(async (value) => {
      const parsed = Number.parseFloat(value);
      this.plugin.settings.rubySizeRatio = Number.isFinite(parsed) ? Math.min(1, Math.max(0.1, parsed)) : 0.5;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u508D\u70B9\u633F\u5165\u5F62\u5F0F").setDesc("\u30B3\u30DE\u30F3\u30C9\u3067\u9078\u629E\u7BC4\u56F2\u306B\u508D\u70B9\u3092\u633F\u5165\u3059\u308B\u3068\u304D\u306E\u5F62\u5F0F\u3067\u3059\u3002").addDropdown((dropdown) => dropdown.addOption("kakuyomu", "\u30AB\u30AF\u30E8\u30E0: \u300A\u300A\u672C\u6587\u300B\u300B").addOption("aozora", "\u9752\u7A7A/\u306A\u308D\u3046: \uFF5C\u672C\u6587\u300A\uFE45\uFE45\u300B").setValue(this.plugin.settings.emphasisInsertFormat).onChange(async (value) => {
      this.plugin.settings.emphasisInsertFormat = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u508D\u70B9\u6587\u5B57").setDesc("\u9752\u7A7A\u6587\u5EAB\u30FB\u306A\u308D\u3046\u5F62\u5F0F\u3067\u633F\u5165\u3059\u308B\u508D\u70B9\u306E\u7A2E\u985E\u3067\u3059\u3002\u7A7A\u306E\u5834\u5408\u306F \uFE45 \u3092\u4F7F\u3044\u307E\u3059\u3002").addText((text) => text.setPlaceholder("\uFE45").setValue(this.plugin.settings.emphasisMark).onChange(async (value) => {
      var _a;
      this.plugin.settings.emphasisMark = (_a = Array.from(value.trim())[0]) != null ? _a : "\uFE45";
      await this.plugin.saveSettingsAndRefresh();
      this.display();
    }));
    containerEl.createEl("h2", { text: "\u6587\u5B57\u6570\u30AB\u30A6\u30F3\u30C8" });
    new import_obsidian.Setting(containerEl).setName("\u6587\u5B57\u6570\u3092\u8868\u793A").setDesc("\u5358\u8A9E\u6570\u3067\u306F\u306A\u304F\u3001\u65E5\u672C\u8A9E\u5C0F\u8AAC\u5411\u3051\u306E\u6587\u5B57\u6570\u3092\u30B9\u30C6\u30FC\u30BF\u30B9\u30D0\u30FC\u306B\u8868\u793A\u3057\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableCharacterCount).onChange(async (value) => {
      this.plugin.settings.enableCharacterCount = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u63A5\u982D\u8F9E").setDesc("\u30B9\u30C6\u30FC\u30BF\u30B9\u30D0\u30FC\u306E\u6587\u5B57\u6570\u306E\u524D\u306B\u8868\u793A\u3059\u308B\u6587\u5B57\u5217\u3067\u3059\u3002").addText((text) => text.setPlaceholder("\u306A\u3057").setValue(this.plugin.settings.countPrefix).onChange(async (value) => {
      this.plugin.settings.countPrefix = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u63A5\u5C3E\u8F9E").setDesc("\u30B9\u30C6\u30FC\u30BF\u30B9\u30D0\u30FC\u306E\u6587\u5B57\u6570\u306E\u5F8C\u306B\u8868\u793A\u3059\u308B\u6587\u5B57\u5217\u3067\u3059\u3002").addText((text) => text.setPlaceholder("\u6587\u5B57").setValue(this.plugin.settings.countSuffix).onChange(async (value) => {
      this.plugin.settings.countSuffix = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("\u898B\u51FA\u3057\u6A2A\u306B\u30BB\u30AF\u30B7\u30E7\u30F3\u6587\u5B57\u6570\u3092\u8868\u793A").setDesc("\u5404\u898B\u51FA\u3057\u304B\u3089\u3001\u6B21\u306E\u540C\u3058\u968E\u5C64\u4EE5\u4E0A\u306E\u898B\u51FA\u3057\u307E\u3067\u3092\u6570\u3048\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHeadingCounts).onChange(async (value) => {
      this.plugin.settings.showHeadingCounts = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    containerEl.createEl("h3", { text: "\u30AB\u30A6\u30F3\u30C8\u5BFE\u8C61" });
    this.addCountToggle("\u7A7A\u767D\u3092\u6570\u3048\u306A\u3044", "excludeWhitespaceFromCount");
    this.addCountToggle("\u6539\u884C\u3092\u6570\u3048\u306A\u3044", "excludeNewlinesFromCount");
    this.addCountToggle("\u30EB\u30D3\u3068\u508D\u70B9\u306E\u8A18\u6CD5\u3092\u6570\u3048\u306A\u3044", "excludeRubyFromCount");
    this.addCountToggle("Obsidian\u306ECallout\u3092\u6570\u3048\u306A\u3044", "excludeCalloutsFromCount");
    this.addCountToggle("Markdown\u30B3\u30E1\u30F3\u30C8\u3092\u6570\u3048\u306A\u3044", "excludeCommentsFromCount");
    new import_obsidian.Setting(containerEl).setName("\u898B\u51FA\u3057\u3092\u6587\u5B57\u6570\u304B\u3089\u9664\u5916").setDesc("# \u898B\u51FA\u3057\u884C\u5168\u4F53\u3092\u6587\u5B57\u6570\u306B\u542B\u3081\u307E\u305B\u3093\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.excludeHeadingsFromCount).onChange(async (value) => {
      this.plugin.settings.excludeHeadingsFromCount = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
    new import_obsidian.Setting(containerEl).setName("Markdown\u5236\u5FA1\u6587\u5B57\u3092\u9664\u5916").setDesc("\u898B\u51FA\u3057\u8A18\u53F7\u3001\u5F37\u8ABF\u8A18\u53F7\u3001\u30EA\u30F3\u30AF\u8A18\u6CD5\u306A\u3069\u3092\u3067\u304D\u308B\u3060\u3051\u672C\u6587\u3060\u3051\u306B\u3057\u3066\u6570\u3048\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.excludeMarkdownControlsFromCount).onChange(async (value) => {
      this.plugin.settings.excludeMarkdownControlsFromCount = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
  }
  addCountToggle(name, key) {
    new import_obsidian.Setting(this.containerEl).setName(name).addToggle((toggle) => toggle.setValue(this.plugin.settings[key]).onChange(async (value) => {
      this.plugin.settings[key] = value;
      await this.plugin.saveSettingsAndRefresh();
    }));
  }
};

// src/main.ts
var JapaneseNovelToolPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.headingSectionCache = /* @__PURE__ */ new Map();
    this.characterCountTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.applyStyleSettings();
    this.statusBarItem = this.addStatusBarItem();
    this.addSettingTab(new JapaneseNovelToolSettingTab(this.app, this));
    this.registerEditorExtension(this.createHeadingCountExtension());
    this.registerEditorExtension(this.createRubyExtension());
    this.registerEditorExtension(this.createInvisiblesExtension());
    this.registerMarkdownPostProcessor((el, ctx) => {
      var _a;
      if (this.settings.enableRubyRendering) {
        renderNovelMarkup(el, this.settings.enableKakuyomuEmphasis);
      }
      if (this.settings.enableIndentation) {
        renderJapaneseIndentation(el, ctx, (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor);
      }
      void this.decorateReadingView(el, ctx);
    });
    this.addCommand({
      id: "insert-japanese-novel-ruby",
      name: "Insert ruby",
      editorCallback: (editor) => insertRuby(editor)
    });
    this.addCommand({
      id: "insert-japanese-novel-emphasis",
      name: "Insert emphasis marks",
      editorCallback: (editor) => insertEmphasis(editor, this.settings.emphasisInsertFormat, this.settings.emphasisMark)
    });
    this.addCommand({
      id: "remove-japanese-novel-markup",
      name: "Remove ruby and emphasis marks from selection",
      editorCallback: (editor) => removeMarkupFromSelection(editor, this.settings.enableKakuyomuEmphasis)
    });
    this.addCommand({
      id: "copy-heading-section-with-heading",
      name: "Copy current section (with heading)",
      editorCallback: (editor) => copyHeadingSection(editor, true)
    });
    this.addCommand({
      id: "copy-heading-section-without-heading",
      name: "Copy current section (without heading)",
      editorCallback: (editor) => copyHeadingSection(editor, false)
    });
    this.registerEvent(this.app.workspace.on("file-open", () => this.updateCharacterCount()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.updateCharacterCount()));
    this.registerEvent(this.app.workspace.on("editor-change", () => this.scheduleCharacterCountUpdate()));
    await this.refreshDisplays();
  }
  onunload() {
    if (this.characterCountTimer !== null) {
      window.clearTimeout(this.characterCountTimer);
      this.characterCountTimer = null;
    }
    this.clearReadingViewCounts();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettingsAndRefresh() {
    await this.saveData(this.settings);
    this.applyStyleSettings();
    await this.refreshDisplays();
  }
  applyStyleSettings() {
    const ratio = Number.isFinite(this.settings.rubySizeRatio) ? Math.min(1, Math.max(0.1, this.settings.rubySizeRatio)) : 0.5;
    document.body.style.setProperty("--jnt-ruby-size", `${ratio}em`);
  }
  async refreshDisplays() {
    this.headingSectionCache.clear();
    this.updateCharacterCount();
    this.app.workspace.updateOptions();
    this.app.workspace.trigger("css-change");
  }
  scheduleCharacterCountUpdate() {
    this.headingSectionCache.clear();
    if (this.characterCountTimer !== null) {
      window.clearTimeout(this.characterCountTimer);
    }
    this.characterCountTimer = window.setTimeout(() => {
      this.characterCountTimer = null;
      this.updateCharacterCount();
    }, 1e3);
  }
  updateCharacterCount() {
    if (!this.statusBarItem) return;
    if (!this.settings.enableCharacterCount) {
      this.statusBarItem.hide();
      return;
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      this.statusBarItem.hide();
      return;
    }
    const selectedText = view.editor.getSelection();
    const target = selectedText.length > 0 ? selectedText : view.editor.getValue();
    const count = countNovelCharacters(target, this.getCountOptions());
    this.statusBarItem.setText(`${this.settings.countPrefix}${formatCount(count)}${this.settings.countSuffix}`);
    this.statusBarItem.show();
  }
  createHeadingCountExtension() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(class {
      constructor(view) {
        this.countsByLine = /* @__PURE__ */ new Map();
        this.sections = [];
        this.pendingFullRebuild = false;
        this.pendingDeltas = /* @__PURE__ */ new Map();
        this.timer = null;
        this.view = view;
        this.rebuildAll(plugin, view);
      }
      update(update) {
        this.view = update.view;
        if (update.docChanged) {
          this.decorations = this.decorations.map(update.changes);
          if (plugin.shouldRebuildAllHeadingDecorations(update)) {
            this.pendingFullRebuild = true;
          } else {
            update.changes.iterChanges((fromA, toA, fromB, _toB, inserted) => {
              var _a;
              const oldText = update.startState.doc.sliceString(fromA, toA);
              const newText = inserted.toString();
              if (!plugin.canUseDeltaHeadingCountUpdate(oldText, newText)) {
                this.pendingFullRebuild = true;
                return;
              }
              const delta = plugin.countTextDelta(oldText, newText);
              if (delta === 0) {
                return;
              }
              const targetLine = update.view.state.doc.lineAt(fromB).number - 1;
              const headings = getHeadingAncestorsFromHeadings(this.sections, targetLine);
              for (const heading of headings) {
                this.pendingDeltas.set(heading.line, ((_a = this.pendingDeltas.get(heading.line)) != null ? _a : 0) + delta);
              }
            });
          }
          this.scheduleFlush();
        }
      }
      destroy() {
        this.clearPending();
      }
      scheduleFlush() {
        if (this.timer !== null) {
          window.clearTimeout(this.timer);
        }
        this.timer = window.setTimeout(() => {
          this.timer = null;
          if (this.pendingFullRebuild) {
            this.rebuildAll(plugin, this.view);
          } else {
            for (const [lineNumber, delta] of this.pendingDeltas) {
              const current = this.countsByLine.get(lineNumber);
              if (current === void 0) {
                this.pendingFullRebuild = true;
                break;
              }
              const next = Math.max(0, current + delta);
              this.countsByLine.set(lineNumber, next);
              this.decorations = plugin.replaceEditorHeadingDecoration(
                this.view,
                this.decorations,
                { line: lineNumber, count: next }
              );
            }
            if (this.pendingFullRebuild) {
              this.rebuildAll(plugin, this.view);
            }
          }
          this.pendingFullRebuild = false;
          this.pendingDeltas.clear();
          this.view.dispatch({});
        }, 700);
      }
      rebuildAll(plugin2, view) {
        const result = plugin2.buildEditorDecorationsWithCounts(view);
        this.decorations = result.decorations;
        this.countsByLine = result.countsByLine;
        this.sections = result.sections;
      }
      clearPending() {
        if (this.timer !== null) {
          window.clearTimeout(this.timer);
          this.timer = null;
        }
        this.pendingFullRebuild = false;
        this.pendingDeltas.clear();
      }
    }, {
      decorations: (value) => value.decorations
    });
  }
  createRubyExtension() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(class {
      constructor(view) {
        this.decorations = plugin.buildRubyDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged || update.selectionSet || update.focusChanged) {
          this.decorations = plugin.buildRubyDecorations(update.view);
        }
      }
    }, {
      decorations: (value) => value.decorations
    });
  }
  buildRubyDecorations(view) {
    var _a, _b, _c, _d;
    if (!this.settings.enableRubyRendering) {
      return import_view.Decoration.none;
    }
    const builder = new import_state.RangeSetBuilder();
    const selections = view.state.selection.ranges;
    let lastLine = -1;
    for (const visibleRange of view.visibleRanges) {
      for (let pos = visibleRange.from; pos <= visibleRange.to; ) {
        const line = view.state.doc.lineAt(pos);
        if (line.number === lastLine) {
          pos = line.to + 1;
          continue;
        }
        lastLine = line.number;
        if (selections.some((range) => range.to >= line.from && range.from <= line.to)) {
          pos = line.to + 1;
          continue;
        }
        const pending = [];
        if (/《[^》]+》/.test(line.text)) {
          NOVEL_RUBY_REGEXP.lastIndex = 0;
          let match;
          while ((match = NOVEL_RUBY_REGEXP.exec(line.text)) !== null) {
            const body = ((_a = match.groups) == null ? void 0 : _a.body1) || ((_b = match.groups) == null ? void 0 : _b.body2);
            const rubyText = (_c = match.groups) == null ? void 0 : _c.ruby;
            if (!body || !rubyText) continue;
            const matchStart = line.from + match.index;
            const matchEnd = matchStart + match[0].length;
            if (selections.some((range) => range.to >= matchStart && range.from <= matchEnd)) {
              continue;
            }
            if (this.isExcludedSyntax(view, matchStart + 1)) {
              continue;
            }
            const fullMatchText = match[0];
            const bodyIndex = fullMatchText.indexOf(body);
            const prefixLength = bodyIndex;
            const isTablePipe = prefixLength === 1 && fullMatchText[0] === "|" && body.startsWith(" ");
            if (prefixLength > 0 && !isTablePipe) {
              pending.push({ from: matchStart, to: matchStart + prefixLength, decoration: import_view.Decoration.replace({}) });
            }
            let rubyContentStart = matchStart + prefixLength;
            if (isTablePipe) {
              rubyContentStart += 1;
              const kanjiMatch = body.match(/[一-龠々仝〆〇ヶ]+$/);
              if (kanjiMatch && body.length - 1 > kanjiMatch[0].length) {
                rubyContentStart = matchStart + prefixLength + (body.length - kanjiMatch[0].length);
              }
            }
            pending.push({
              from: rubyContentStart,
              to: matchEnd,
              decoration: import_view.Decoration.mark({ tagName: "ruby", class: "jnt-ruby" })
            });
            const bodyEndRel = bodyIndex + body.length;
            const startDelimStart = matchStart + bodyEndRel;
            const startDelimEnd = startDelimStart + "\u300A".length;
            pending.push({ from: startDelimStart, to: startDelimEnd, decoration: import_view.Decoration.replace({}) });
            const rubyStart = startDelimEnd;
            const rubyEnd = rubyStart + rubyText.length;
            if (rubyEnd > rubyStart) {
              pending.push({ from: rubyStart, to: rubyEnd, decoration: import_view.Decoration.mark({ tagName: "rt" }) });
            }
            const endDelimStart = rubyEnd;
            const endDelimEnd = matchEnd;
            if (endDelimEnd > endDelimStart) {
              pending.push({ from: endDelimStart, to: endDelimEnd, decoration: import_view.Decoration.replace({}) });
            }
          }
        }
        if (this.settings.enableKakuyomuEmphasis) {
          KAKUYOMU_EMPHASIS_REGEXP.lastIndex = 0;
          let emphasisMatch;
          while ((emphasisMatch = KAKUYOMU_EMPHASIS_REGEXP.exec(line.text)) !== null) {
            const body = (_d = emphasisMatch.groups) == null ? void 0 : _d.body;
            if (!body) continue;
            const matchStart = line.from + emphasisMatch.index;
            const matchEnd = matchStart + emphasisMatch[0].length;
            if (selections.some((range) => range.to >= matchStart && range.from <= matchEnd)) {
              continue;
            }
            if (this.isExcludedSyntax(view, matchStart + 1)) {
              continue;
            }
            const bodyStart = matchStart + "\u300A\u300A".length;
            const bodyEnd = bodyStart + body.length;
            pending.push({ from: matchStart, to: bodyStart, decoration: import_view.Decoration.replace({}) });
            pending.push({
              from: bodyStart,
              to: bodyEnd,
              decoration: import_view.Decoration.mark({ class: "jnt-emphasis" })
            });
            pending.push({ from: bodyEnd, to: matchEnd, decoration: import_view.Decoration.replace({}) });
          }
        }
        pending.sort((a, b) => a.from - b.from || a.to - b.to).forEach((item) => builder.add(item.from, item.to, item.decoration));
        pos = line.to + 1;
      }
    }
    return builder.finish();
  }
  createInvisiblesExtension() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(class {
      constructor(view) {
        this.decorations = plugin.buildInvisibleDecorations(view);
        this.builtWithWhitespace = plugin.settings.showWhitespaceMarks;
        this.builtWithLineBreaks = plugin.settings.showLineBreakMarks;
      }
      update(update) {
        const settingsChanged = this.builtWithWhitespace !== plugin.settings.showWhitespaceMarks || this.builtWithLineBreaks !== plugin.settings.showLineBreakMarks;
        if (update.docChanged || update.viewportChanged || settingsChanged) {
          this.decorations = plugin.buildInvisibleDecorations(update.view);
          this.builtWithWhitespace = plugin.settings.showWhitespaceMarks;
          this.builtWithLineBreaks = plugin.settings.showLineBreakMarks;
        }
      }
    }, {
      decorations: (value) => value.decorations
    });
  }
  buildInvisibleDecorations(view) {
    const showWhitespace = this.settings.showWhitespaceMarks;
    const showLineBreaks = this.settings.showLineBreakMarks;
    if (!showWhitespace && !showLineBreaks) {
      return import_view.Decoration.none;
    }
    const builder = new import_state.RangeSetBuilder();
    const lastLineNumber = view.state.doc.lines;
    let lastLine = -1;
    for (const visibleRange of view.visibleRanges) {
      for (let pos = visibleRange.from; pos <= visibleRange.to; ) {
        const line = view.state.doc.lineAt(pos);
        if (line.number === lastLine) {
          pos = line.to + 1;
          continue;
        }
        lastLine = line.number;
        if (showWhitespace) {
          let excludedRanges = null;
          if (this.settings.enableRubyRendering && line.text.includes("\u300A")) {
            excludedRanges = [];
            NOVEL_RUBY_REGEXP.lastIndex = 0;
            let rubyMatch;
            while ((rubyMatch = NOVEL_RUBY_REGEXP.exec(line.text)) !== null) {
              excludedRanges.push({ from: rubyMatch.index, to: rubyMatch.index + rubyMatch[0].length });
            }
          }
          WHITESPACE_MARK_REGEXP.lastIndex = 0;
          let match;
          while ((match = WHITESPACE_MARK_REGEXP.exec(line.text)) !== null) {
            const indexInLine = match.index;
            if (excludedRanges == null ? void 0 : excludedRanges.some((range) => indexInLine >= range.from && indexInLine < range.to)) {
              continue;
            }
            const from = line.from + indexInLine;
            const className = match[0] === "\u3000" ? "jnt-ws-full" : "jnt-ws-tab";
            builder.add(from, from + 1, import_view.Decoration.mark({ class: className }));
          }
        }
        if (showLineBreaks && line.number < lastLineNumber) {
          builder.add(line.to, line.to, import_view.Decoration.widget({ widget: LINE_BREAK_WIDGET, side: 2 }));
        }
        pos = line.to + 1;
      }
    }
    return builder.finish();
  }
  isExcludedSyntax(view, pos) {
    var _a, _b;
    const node = (0, import_language.syntaxTree)(view.state).resolve(pos);
    const nodeName = node.name;
    const parentName = (_b = (_a = node.parent) == null ? void 0 : _a.name) != null ? _b : "";
    return /code|image/i.test(nodeName) || /code|image/i.test(parentName);
  }
  buildEditorDecorationsWithCounts(view) {
    if (!this.settings.showHeadingCounts) {
      return { decorations: import_view.Decoration.none, countsByLine: /* @__PURE__ */ new Map(), sections: [] };
    }
    const sections = getHeadingSections(view.state.doc.toString(), this.getCountOptions());
    const countsByLine = /* @__PURE__ */ new Map();
    const decorations = sections.map((section) => {
      countsByLine.set(section.line, section.count);
      const line = view.state.doc.line(section.line + 1);
      return import_view.Decoration.widget({
        widget: new HeadingCountWidget(section.count),
        side: 1
      }).range(line.to);
    });
    return { decorations: import_view.Decoration.set(decorations, true), countsByLine, sections };
  }
  replaceEditorHeadingDecoration(view, decorations, section) {
    const line = view.state.doc.line(section.line + 1);
    return decorations.update({
      filter: (from) => from !== line.to,
      add: [import_view.Decoration.widget({
        widget: new HeadingCountWidget(section.count),
        side: 1
      }).range(line.to)],
      sort: true
    });
  }
  countTextDelta(oldText, newText) {
    return countNovelCharacters(newText, this.getCountOptions()) - countNovelCharacters(oldText, this.getCountOptions());
  }
  canUseDeltaHeadingCountUpdate(oldText, newText) {
    const changedText = oldText + newText;
    if (/[\r\n]/.test(changedText)) {
      return false;
    }
    if (/[#*_~=`>\[\]()!|｜《》﹅﹆・]/.test(changedText)) {
      return false;
    }
    return true;
  }
  shouldRebuildAllHeadingDecorations(update) {
    let shouldRebuild = false;
    let changeCount = 0;
    update.changes.iterChangedRanges((fromA, _toA, fromB, toB) => {
      changeCount += 1;
      if (changeCount > 1) {
        shouldRebuild = true;
        return;
      }
      if (shouldRebuild) {
        return;
      }
      const changedText = update.view.state.doc.sliceString(fromB, toB);
      const line = update.view.state.doc.lineAt(fromB);
      const oldLine = update.startState.doc.lineAt(fromA);
      shouldRebuild = /^\s{0,3}#{1,6}\s/.test(oldLine.text) || /^#{1,6}\s/.test(line.text) || /\n\s{0,3}#{1,6}\s/.test(changedText) || /^[=-]+$/.test(oldLine.text.trim()) || /^[=-]+$/.test(line.text.trim());
    });
    return shouldRebuild;
  }
  async decorateReadingView(element, context) {
    var _a;
    if (!this.settings.showHeadingCounts) {
      return;
    }
    const headings = Array.from(element.querySelectorAll("h1, h2, h3, h4, h5, h6"));
    if (headings.length === 0) {
      return;
    }
    const file = this.app.vault.getAbstractFileByPath(context.sourcePath);
    if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md") {
      return;
    }
    const sections = await this.getCachedHeadingSections(file);
    const sectionInfo = context.getSectionInfo(element);
    for (const heading of headings) {
      if (heading.querySelector(".jnt-heading-count-reading")) {
        continue;
      }
      const level = Number.parseInt(heading.tagName.slice(1), 10);
      const section = this.findReadingSection(sections, level, (_a = heading.textContent) != null ? _a : "", sectionInfo == null ? void 0 : sectionInfo.lineStart);
      if (!section) {
        continue;
      }
      const countElement = document.createElement("span");
      countElement.className = "jnt-heading-count jnt-heading-count-reading";
      countElement.textContent = formatCount(section.count);
      heading.appendChild(countElement);
    }
  }
  async getCachedHeadingSections(file) {
    const cached = this.headingSectionCache.get(file.path);
    if (cached && cached.mtime === file.stat.mtime) {
      return cached.sections;
    }
    const source = await this.app.vault.cachedRead(file);
    const sections = getHeadingSections(source, this.getCountOptions());
    this.headingSectionCache.set(file.path, { mtime: file.stat.mtime, sections });
    return sections;
  }
  findReadingSection(sections, level, text, lineStart) {
    const normalizedText = text.replace(/\d[\d,]*$/, "").trim();
    const exactLine = lineStart === void 0 ? void 0 : sections.find((section) => section.line === lineStart && section.level === level);
    return exactLine != null ? exactLine : sections.find((section) => section.level === level && section.text === normalizedText);
  }
  clearReadingViewCounts() {
    document.querySelectorAll(".jnt-heading-count-reading").forEach((element) => element.remove());
  }
  getCountOptions() {
    return {
      excludeWhitespace: this.settings.excludeWhitespaceFromCount,
      excludeNewlines: this.settings.excludeNewlinesFromCount,
      excludeRuby: this.settings.excludeRubyFromCount,
      excludeCallouts: this.settings.excludeCalloutsFromCount,
      excludeComments: this.settings.excludeCommentsFromCount,
      excludeHeadings: this.settings.excludeHeadingsFromCount,
      excludeMarkdownControls: this.settings.excludeMarkdownControlsFromCount,
      enableKakuyomuEmphasis: this.settings.enableKakuyomuEmphasis
    };
  }
};
var WHITESPACE_MARK_REGEXP = /[\t　]/g;
var LineBreakWidget = class extends import_view.WidgetType {
  toDOM() {
    const element = document.createElement("span");
    element.className = "jnt-line-break-mark";
    element.textContent = "\u21B5";
    return element;
  }
  eq() {
    return true;
  }
  ignoreEvent() {
    return true;
  }
};
var LINE_BREAK_WIDGET = new LineBreakWidget();
var HeadingCountWidget = class extends import_view.WidgetType {
  constructor(count) {
    super();
    this.count = count;
  }
  toDOM() {
    const element = document.createElement("span");
    element.className = "jnt-heading-count jnt-heading-count-editor-widget";
    element.textContent = formatCount(this.count);
    return element;
  }
  eq(other) {
    return other.count === this.count;
  }
};
function renderNovelMarkup(root, enableKakuyomuEmphasis) {
  var _a, _b;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      if (parent.closest("code, pre, script, style, ruby")) return NodeFilter.FILTER_REJECT;
      if (!node.nodeValue || !/[｜《》]/.test(node.nodeValue)) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    }
  });
  const nodes = [];
  while (walker.nextNode()) {
    nodes.push(walker.currentNode);
  }
  for (const node of nodes) {
    const fragment = document.createDocumentFragment();
    const tokens = parseNovelMarkup((_a = node.nodeValue) != null ? _a : "", enableKakuyomuEmphasis);
    let changed = false;
    for (const token of tokens) {
      if (token.type === "text") {
        fragment.appendText(token.text);
        continue;
      }
      changed = true;
      if (token.type === "ruby") {
        const ruby = document.createElement("ruby");
        ruby.addClass("jnt-ruby");
        ruby.appendText(token.base);
        const rt = document.createElement("rt");
        rt.appendText(token.ruby);
        ruby.appendChild(rt);
        fragment.appendChild(ruby);
        continue;
      }
      const span = document.createElement("span");
      span.addClass("jnt-emphasis");
      span.appendText(token.text);
      fragment.appendChild(span);
    }
    if (changed) {
      (_b = node.parentNode) == null ? void 0 : _b.replaceChild(fragment, node);
    }
  }
}
function renderJapaneseIndentation(root, context, editor) {
  const paragraph = root.querySelector("p");
  if (!paragraph || !editor) {
    return;
  }
  const sectionInfo = context.getSectionInfo(root);
  if (!sectionInfo) {
    return;
  }
  const editorLines = getEditorLines(editor, sectionInfo.lineStart, sectionInfo.lineEnd);
  const childNodes = formattedIndentChildNodes(paragraph, editorLines);
  paragraph.replaceChildren(...childNodes);
}
function formattedIndentChildNodes(paragraph, editorLines) {
  const lines = editorLines.slice(1);
  return Array.from(paragraph.childNodes).map((childNode) => {
    var _a;
    const text = childNode.textContent;
    if (text == null) {
      return childNode;
    }
    if (childNode.nodeName === "#text" && text.startsWith("\n")) {
      const line = lines.shift();
      if (line == null) {
        return childNode;
      }
      const space = (_a = line.match(/^\s+/)) == null ? void 0 : _a[0];
      if (space == null) {
        return childNode;
      }
      const chars = Array.from(text);
      chars.splice(1, 0, space);
      const clone = childNode.cloneNode();
      clone.textContent = chars.join("");
      return clone;
    }
    return childNode;
  });
}
function getEditorLines(editor, lineStart, lineEnd) {
  var _a;
  const editorLines = [];
  for (let lineNumber = lineStart; lineNumber <= lineEnd; lineNumber += 1) {
    const line = editor.getLine(lineNumber);
    if (line == null) {
      continue;
    }
    if (/^ *> ?\[!.+?\]/.test(line)) {
      continue;
    }
    const quoteSymbol = (_a = line.match(/^((>| )*)?>/)) == null ? void 0 : _a[0];
    if (quoteSymbol != null) {
      const chars = Array.from(line);
      chars.splice(0, quoteSymbol.length);
      editorLines.push(chars.join(""));
      continue;
    }
    editorLines.push(line);
  }
  return editorLines;
}
function insertRuby(editor) {
  const selection = editor.getSelection();
  const text = selection.length > 0 ? `\uFF5C${selection}\u300A\u300B` : "\uFF5C\u300A\u300B";
  editor.replaceSelection(text);
  const cursor = editor.getCursor();
  editor.setCursor({ line: cursor.line, ch: Math.max(0, cursor.ch - 1) });
}
function insertEmphasis(editor, format, emphasisMark) {
  var _a;
  const selection = editor.getSelection();
  if (format === "aozora") {
    const mark = (_a = Array.from(emphasisMark.trim())[0]) != null ? _a : "\uFE45";
    const markCount = Math.max(1, Array.from(selection.replace(/\r?\n/g, "")).length);
    editor.replaceSelection(selection.length > 0 ? `\uFF5C${selection}\u300A${mark.repeat(markCount)}\u300B` : `\uFF5C\u300A${mark}\u300B`);
    return;
  }
  editor.replaceSelection(selection.length > 0 ? `\u300A\u300A${selection}\u300B\u300B` : "\u300A\u300A\u300B\u300B");
  if (selection.length === 0) {
    const cursor = editor.getCursor();
    editor.setCursor({ line: cursor.line, ch: Math.max(0, cursor.ch - 2) });
  }
}
function removeMarkupFromSelection(editor, enableKakuyomuEmphasis) {
  const selection = editor.getSelection();
  if (selection.length === 0) return;
  editor.replaceSelection(removeNovelMarkup(selection, enableKakuyomuEmphasis));
}
function copyHeadingSection(editor, includeHeading) {
  const source = editor.getValue();
  const offset = editor.posToOffset(editor.getCursor());
  const range = getHeadingSectionRangeAtOffset(source, offset);
  if (!range) {
    new import_obsidian2.Notice("\u898B\u51FA\u3057\u30BB\u30AF\u30B7\u30E7\u30F3\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093");
    return;
  }
  const lines = source.split(/\r\n|\r|\n/);
  const startLine = includeHeading ? range.headingLine : range.bodyStartLine;
  const text = lines.slice(startLine, range.endLine).join("\n").replace(/\n+$/, "");
  if (text.length === 0) {
    new import_obsidian2.Notice("\u30B3\u30D4\u30FC\u3059\u308B\u672C\u6587\u304C\u3042\u308A\u307E\u305B\u3093");
    return;
  }
  void navigator.clipboard.writeText(text).then(
    () => new import_obsidian2.Notice(includeHeading ? "\u30BB\u30AF\u30B7\u30E7\u30F3\u3092\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F(\u898B\u51FA\u3057\u3092\u542B\u3080)" : "\u30BB\u30AF\u30B7\u30E7\u30F3\u3092\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F(\u898B\u51FA\u3057\u3092\u9664\u304F)"),
    () => new import_obsidian2.Notice("\u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u3078\u306E\u30B3\u30D4\u30FC\u306B\u5931\u6557\u3057\u307E\u3057\u305F")
  );
}
